# Generated by Django 5.0.6 on 2024-07-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='scannedproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.product'),
            preserve_default=False,
        ),
    ]
